<a href="https://colab.research.google.com/github/sanchitasontakke07-exe/Python-Basic-Projects/blob/main/d13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr1=np.array([10,20,30,40,50])
print("1D Array :",arr1)
print("Array shape :",arr1.shape)
print("Array type :",arr1.dtype)

1D Array : [10 20 30 40 50]
Array shape : (5,)
Array type : int64


In [ ]:
arr2=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("2D Array (3 x 3):",arr2)
print("Array shape :",arr2.shape)
print("Array type :",arr2.dtype)

2D Array (3 x 3): [[10 20 30]
 [40 50 60]
 [70 80 90]]
Array shape : (3, 3)
Array type : int64


In [15]:
import numpy as np
arr3=np.zeros(8)
print("1D Array of Zeros:",arr3)
arr4=np.ones((4,4))
print("2D Array of Shape(4,4) with ones:",arr4)
arr5=np.zeros((3,3))
print("3x3 matrix of Zeros:",arr5)

1D Array of Zeros: [0. 0. 0. 0. 0. 0. 0. 0.]
2D Array of Shape(4,4) with ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
3x3 matrix of Zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [31]:
import numpy as np
a=np.arange(0,21,1)
print("Numbersfrom 0 to 20 :",a)
b = np.arange(10,51,2)
print("Even numbers from 10 to 50 :",b)
c=np.arange(5,100,5)
print("Numbers from 5 to 100 step of 5",c)

Numbersfrom 0 to 20 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Even numbers from 10 to 50 : [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
Numbers from 5 to 100 step of 5 : [ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [50]:
import numpy as np
a=np.linspace(0,5,10)
print("10 equally spaced no. between 0 and 5 :",a)
print("Length a :",len(a))
b=np.linspace(-10,10,15)
print("15 equally spaced no.between -10 and 10  :",b)
print("Length b :",len(b))

10 equally spaced no. between 0 and 5 : [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length a : 10
15 equally spaced no.between -10 and 10  : [-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
Length b : 15


In [57]:
import numpy as np
a=np.random.rand(10)
print("1D random array between 0 and 1:",a)
b=np.random.rand(3,3)
print("3x3 random matrix :",b)
c=np.random.randint(10,51,(4,5))
print("2D array (4,5) between 10 to 50:",c)

1D random array between 0 and 1: [0.66924262 0.04911981 0.46508208 0.93801887 0.85763264 0.52904245
 0.50672871 0.32658036 0.36451598 0.59952748]
3x3 random matrix : [[0.96312757 0.13244494 0.9133723 ]
 [0.58456705 0.0766583  0.75857348]
 [0.3502293  0.68028846 0.76609135]]
2D array (4,5) between 10 to 50: [[45 16 49 27 38]
 [47 30 15 39 30]
 [47 12 21 16 43]
 [38 45 17 10 14]]


In [59]:
import numpy as np
v1=np.array([2,4,6,8])
v2=np.array([1,3,5,7])
print("v1 :",v1)
print("v2 :",v2)
print("Addition :",v1+v2)
print("Subtraction :",v1-v2)
print("Multiplication :",v1*v2)
print("Dot Product :",np.dot(v1,v2))

v1 : [2 4 6 8]
v2 : [1 3 5 7]
Addition : [ 3  7 11 15]
Subtraction : [1 1 1 1]
Multiplication : [ 2 12 30 56]
Dot Product : 100


In [63]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[9,8,7],[6,5,4],[3,2,1]])
print("A :",A)
print("B:",B)
print("Addition :",A+B)
print("Multiplication using dot :",np.dot(A,B))
print("Multiplication :",A*B)

A : [[1 2 3]
 [4 5 6]
 [7 8 9]]
B: [[9 8 7]
 [6 5 4]
 [3 2 1]]
Addition : [[10 10 10]
 [10 10 10]
 [10 10 10]]
Multiplication using dot : [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Multiplication : [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [67]:
import numpy as np
x=np.random.randint(1,101,(4,4))
print("X:",x)
print("Shape :",x.shape)
print("Dimension :",x.ndim)
print("Size:",x.size)
print("Data Type :",x.dtype)
print("Minimum:",x.min())
print("Maximum:",x.max())

X: [[17 94 97 47]
 [27 38 50 24]
 [ 2 58  6 76]
 [92 13 52 77]]
Shape : (4, 4)
Dimension : 2
Size: 16
Data Type : int64
Minimum: 2
Maximum: 97


In [72]:
import numpy as np
a =np.random.randint(1,51,20)
b=a.reshape(4,5)
print("4x5 Matrix :",b)
print("\nSum:",b.sum())
print("Mean:",b.mean())
print("Standard Deviation :",b.std())
print("\nMaximum value in each row:",b.max(axis=1))

4x5 Matrix : [[29 50 14 36 46]
 [40 20 30  8  7]
 [35 29 10 12  7]
 [31 50 31 16 14]]

Sum: 515
Mean: 25.75
Standard Deviation : 14.02453207775575

Maximum value in each row: [50 40 35 50]


In [75]:
import numpy as np
n=int(input("Enter how many numbers :"))
arr=np.random.randint(10,101,n)
print("Array:",arr)
print("Mean :",np.mean(arr))
print("Median :",np.median(arr))
print("Standard Deviation :",np.std(arr))
print("Minimum :",np.min(arr))
print("maximum :",np.max(arr))
if n%2 == 0:
  arr2 =arr.reshape(2, n//2)
  print("\n2D Array :",arr2)
  print("Row wise sum :",np.sum(arr2,axis=1))
else:
  print("Cannot reshape into 2D array.")

Enter how many numbers :6
Array: [41 38 68 93 22 69]
Mean : 55.166666666666664
Median : 54.5
Standard Deviation : 23.7445900271105
Minimum : 22
maximum : 93

2D Array : [[41 38 68]
 [93 22 69]]
Row wise sum : [147 184]
