<a href="https://colab.research.google.com/github/sanchitasontakke07-exe/Python-Basic-Projects/blob/main/D14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
arr1 = np.random.randint(10,101,(5,6))
print("2D Array :",arr1)
print("Shape :",arr1.shape)
print("Total no of elements :",arr1.size)
print("Data Type :",arr1.dtype)

2D Array : [[48 68 33 73 10 49]
 [91 92 21 85 43 13]
 [60 44 55 33 57 80]
 [64 67 24 24 71 58]
 [56 54 55 76 16 88]]
Shape : (5, 6)
Total no of elements : 30
Data Type : int64


In [30]:
arr2 = np.random.randint(1,51,20)
print("1D Array :",arr2)
print("Minimum Value :",arr2.argmin())
print("Maximum Value:",arr2.argmax())
print("Sum :",arr2.sum())
print("Mean :",arr2.mean())
print("Standard Deviation :",arr2.std())

1D Array : [12 42  8 33 38 47  8 14 42 33 23 30 50  9 24 45 15 25 32 50]
Minimum Value : 2
Maximum Value: 12
Sum : 580
Mean : 29.0
Standard Deviation : 14.127986409959489


In [39]:
arr3 = np.random.randint(20,80,(4,5))
print("Matrix 4x5 :",arr3)
print("Minimum value:",arr3.min())
print("Maximum :",arr3.max())
print("Sum of all elements :",arr3.sum())
print("Mean :",arr3.mean())
print("Standard Deviation :",arr3.std())
print("Sum of each row :",arr3.sum(axis=1))
print("Sum of each Column :",arr3.sum(axis=0))

Matrix 4x5 : [[21 49 50 68 73]
 [35 62 75 43 70]
 [32 71 28 50 55]
 [42 28 48 31 31]]
Minimum value: 21
Maximum : 75
Sum of all elements : 962
Mean : 48.1
Standard Deviation : 16.753805537847214
Sum of each row : [261 285 236 180]
Sum of each Column : [130 210 201 192 229]


In [52]:
import numpy as np
arr4 = np.arange(1,25)
a= arr4.reshape(4,6)
b= arr4.reshape(3,8)
c= arr4.reshape(2,3,4)
print("4x6 :",a)
print("Shape :",a.shape)
print("3x8 :",b)
print("Shape :",b.shape)
print("2x3x4 :",c)
print("Shape :",c.shape)

4x6 : [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape : (4, 6)
3x8 : [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
Shape : (3, 8)
2x3x4 : [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape : (2, 3, 4)


In [61]:
arr = np.array([[10, 20, 30, 40],
[50, 60, 70, 80],
[90, 100, 110, 120]])
print("Array :",arr)
print("First row :",arr[0])
print("Last column :",arr[:,-1])
print("Center 2x2 submatrix :",arr[1:3,1:3])
print("Even Numbers :",arr[arr%2==0])

Array : [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
First row : [10 20 30 40]
Last column : [ 40  80 120]
Center 2x2 submatrix : [[ 60  70]
 [100 110]]
Even Numbers : [ 10  20  30  40  50  60  70  80  90 100 110 120]


In [72]:
import numpy as np
arr5 = np.random.randint(1,101,(5,5))
print("5x5 Matrix :",arr5)
print("Diagonal Elements :",np.diagonal(arr5))
print("Elements greater than 50:",arr6[arr5>50])
arr5[arr5<30]=0
print("Modified Matrix :",arr5)

5x5 Matrix : [[42 13 85 47 70]
 [25 19 10 44 64]
 [47  1 60 20 23]
 [22 33 18 19  6]
 [44 27  8 34 78]]
Diagonal Elements : [42 19 60 19 78]
Elements greater than 50: [ 96 100  57  56  96]
Modified Matrix : [[42  0 85 47 70]
 [ 0  0  0 44 64]
 [47  0 60  0  0]
 [ 0 33  0  0  0]
 [44  0  0 34 78]]


In [84]:
import numpy as np
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print("Array a:", a)
print("Array b:", b)
print("\nAddition:",a+b)
print("\nSubtraction:",a - b)
print("\nMultiplication:",a*b)
print("\nDivision:",a/b)
print("\nElement-wise Power:",a**b)
print("\nModulo Operation:",a%b)

Array a: [10 20 30 40]
Array b: [1 2 3 4]

Addition: [11 22 33 44]

Subtraction: [ 9 18 27 36]

Multiplication: [ 10  40  90 160]

Division: [10. 10. 10. 10.]

Element-wise Power: [     10     400   27000 2560000]

Modulo Operation: [0 0 0 0]


In [85]:
A = np.array ([[1,2,3],[4,5,6],[7,8,9]])
B = np.array ([[9,8,7],[6,5,4],[3,2,1]])
print("Matrix A:",A)
print("Matrix B:",B)
print("Elements-wise Multiplication :",A*B)
print("Matrix Multiplication :",A@B)


Matrix A: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B: [[9 8 7]
 [6 5 4]
 [3 2 1]]
Elements-wise Multiplication : [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix Multiplication : [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [93]:
import numpy as np
arr = np.random.randn(6, 6)
print("Array:",arr)
print("\nShape:",arr.shape)
print("\nSize:",arr.size)
print("\nData Type:",arr.dtype)
print("\nIndex of Maximum Value:",np.unravel_index(np.argmax(arr), arr.shape))
print("\nIndex of Minimum Value:",np.unravel_index(np.argmin(arr), arr.shape))
print("\nTop-left 3x3 Submatrix:",arr[:3, :3])
arr = np.abs(arr)
print("\nModified Matrix:",arr)
print("\nMean of Modified Matrix:",np.mean(arr))

Array: [[-1.48714797  1.40238437  1.26848229  0.04273259 -0.84794342  0.57725759]
 [-1.02443662 -0.68790792  0.34997532 -0.43838524  0.54979391 -1.18445346]
 [ 0.62050455 -0.74389055  2.09081318 -0.8654529   1.01232118  0.44198003]
 [-0.89213132 -0.52316867 -2.46248536  1.27683445 -0.20473322 -0.08940868]
 [ 0.86232102  0.41386514 -0.36460831 -0.59451338  1.76781626  0.21994278]
 [-1.35854225 -0.16005002  2.26474385 -1.40980325 -1.16432522  1.22945895]]

Shape: (6, 6)

Size: 36

Data Type: float64

Index of Maximum Value: (np.int64(5), np.int64(2))

Index of Minimum Value: (np.int64(3), np.int64(2))

Top-left 3x3 Submatrix: [[-1.48714797  1.40238437  1.26848229]
 [-1.02443662 -0.68790792  0.34997532]
 [ 0.62050455 -0.74389055  2.09081318]]

Modified Matrix: [[1.48714797 1.40238437 1.26848229 0.04273259 0.84794342 0.57725759]
 [1.02443662 0.68790792 0.34997532 0.43838524 0.54979391 1.18445346]
 [0.62050455 0.74389055 2.09081318 0.8654529  1.01232118 0.44198003]
 [0.89213132 0.52316867 2

In [97]:
import numpy as np
marks=np.random.randint(30,101,(10,5))
print("Student Marks :",marks)
# Calculate total and average
total=np.sum(marks,axis=1)
average=np.mean(marks,axis=1)
print("Total Marks :",total)
print("Average Marks :",average)
# Find highest and lowest scorer
print("Highest Total Marks Student Index :",np.argmax(total))
print("Lowest Total Marks Student Index :",np.argmin(total))
print("Class Mean :",np.mean(marks))
print("Class Standard Deviation :",np.std(marks))
# Top 3 students
top3=np.argsort(total)[-3:]
print("Top 3 Students Marks :",marks[top3])

Student Marks : [[ 73  67  30  78  62]
 [ 64  31  82  92  96]
 [ 36 100  47  36  47]
 [ 98  66  57  56  65]
 [ 64  30  37  67  88]
 [ 88  67  52  97  74]
 [ 70  38  83  97  68]
 [ 95  40  52  62  62]
 [ 74  60  58  87  54]
 [ 75  52  59  66  87]]
Total Marks : [310 365 266 342 286 378 356 311 333 339]
Average Marks : [62.  73.  53.2 68.4 57.2 75.6 71.2 62.2 66.6 67.8]
Highest Total Marks Student Index : 5
Lowest Total Marks Student Index : 2
Class Mean : 65.72
Class Standard Deviation : 19.54179111545306
Top 3 Students Marks : [[70 38 83 97 68]
 [64 31 82 92 96]
 [88 67 52 97 74]]
